# Generated by Django 4.1.4 on 2022-12-27 15:37

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0002_pax_retired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('associated_city', models.CharField(blank=True, max_length=200, null=True)),
                ('associated_country', django_countries.fields.CountryField(max_length=2)),
                ('associated_territory', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('members', models.ManyToManyField(related_name='region_members', to='registration.pax')),
                ('nantan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_nantan', to='registration.pax')),
                ('weasel_shaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_weasel_shaker', to='registration.pax')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('gps_long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('gps_lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('street_address', models.CharField(max_length=240)),
                ('street_address2', models.CharField(max_length=240)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_site_q', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_q', to='registration.pax')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.region')),
                ('site_qs', models.ManyToManyField(related_name='site_committee', to='registration.pax')),
            ],
        ),
    ]
