# Generated by Django 4.1.5 on 2023-01-09 00:28

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfOperationFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ao_flavor', models.CharField(max_length=64)),
                ('retired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfOperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ao_type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('associated_city', models.CharField(blank=True, max_length=200, null=True)),
                ('associated_country', django_countries.fields.CountryField(max_length=2)),
                ('associated_territory', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('comz_team', models.ManyToManyField(related_name='region_comz_members', to='registration.pax')),
                ('first_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_1st_f', to='registration.pax')),
                ('members', models.ManyToManyField(related_name='region_members', to='registration.pax')),
                ('nantan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_nantan', to='registration.pax')),
                ('second_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_2nd_f', to='registration.pax')),
                ('third_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_3rd_f', to='registration.pax')),
                ('weasel_shaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_weasel_shaker', to='registration.pax')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('gps_long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('gps_lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('street_address', models.CharField(max_length=240)),
                ('street_address2', models.CharField(max_length=240)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('ao_flavors', models.ManyToManyField(related_name='ao_flavors', to='geography.areaofoperationflavor')),
                ('ao_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geography.areaofoperationtype')),
                ('primary_site_q', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='site_q', to='registration.pax')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.region')),
                ('site_qs', models.ManyToManyField(related_name='site_committee', to='registration.pax')),
            ],
        ),
    ]
