# Generated by Django 4.1.4 on 2022-12-13 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f3_handle', models.CharField(max_length=80)),
                ('cell_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('sms_subscribed', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_subscribed', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=90)),
                ('platform_site', models.URLField(blank=True, null=True)),
                ('platform_target', models.URLField(blank=True, null=True)),
                ('platform_android_link', models.URLField(blank=True, null=True)),
                ('platform_ios_link', models.URLField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_pax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.pax')),
                ('social_media_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.socialmediaplatform')),
            ],
        ),
    ]
