# Generated by Django 4.1.4 on 2022-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pax',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
